spring:
  application:
    name: povod

bot:
  name: HolidayEveryDayAllWorldBot
  token: 8138175480:AAHfbtXNcKms2h5KUcIeqnDsRqTNPcyH_gM

integration:
  holiday-services:
    nager-date:
      url: "https://date.nager.at"
      connect-timeout: 1s
      read-timeout: 30s
    rest-countries:
      url: "https://restcountries.com"
      connect-timeout: 1s
      read-timeout: 30s

logging:
  enabled: true
  level:
    root: info

